"""Create a PowerPoint presentation from the video walkthrough script.

Each scene becomes a slide with:
- Title
- Key bullet points extracted from narration
- Screenshot properly sized
- Full narration text as speaker notes
"""

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pathlib import Path

DOCS = Path(__file__).parent.parent / "docs"
SCREENSHOTS = DOCS / "writeup_screenshots"
ASSETS = DOCS / "video_assets"
OUTPUT = DOCS / "STDN_Explorer_Presentation.pptx"

# Dark theme colors
BG_COLOR = RGBColor(0x0F, 0x17, 0x29)
TITLE_COLOR = RGBColor(0xE2, 0xE8, 0xF0)
BULLET_COLOR = RGBColor(0xCB, 0xD5, 0xE1)
ACCENT_COLOR = RGBColor(0xF5, 0x9E, 0x0B)  # amber
SUBTLE_COLOR = RGBColor(0x94, 0xA3, 0xB8)

prs = Presentation()
prs.slide_width = Inches(13.333)  # 16:9 widescreen
prs.slide_height = Inches(7.5)

# Use blank layout
blank_layout = prs.slide_layouts[6]


def set_slide_bg(slide, color=BG_COLOR):
    """Set solid background color for a slide."""
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = color


def add_title(slide, text, left=0.5, top=0.3, width=12.3, size=28):
    """Add a title text box."""
    txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(0.8))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(size)
    p.font.color.rgb = TITLE_COLOR
    p.font.bold = True
    return txBox


def add_subtitle(slide, text, left=0.5, top=1.0):
    """Add a subtitle/section label."""
    txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(12.3), Inches(0.5))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(14)
    p.font.color.rgb = ACCENT_COLOR
    p.font.bold = True


def add_bullets(slide, bullets, left=0.5, top=1.5, width=5.5, size=16):
    """Add bullet points."""
    txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(5.0))
    tf = txBox.text_frame
    tf.word_wrap = True
    for i, bullet in enumerate(bullets):
        if i == 0:
            p = tf.paragraphs[0]
        else:
            p = tf.add_paragraph()
        p.text = bullet
        p.font.size = Pt(size)
        p.font.color.rgb = BULLET_COLOR
        p.space_after = Pt(12)
        p.level = 0
    return txBox


def add_image(slide, img_path, left=6.5, top=1.5, width=6.3):
    """Add an image, maintaining aspect ratio."""
    if not img_path.exists():
        print(f"  WARNING: {img_path} not found")
        return
    pic = slide.shapes.add_picture(str(img_path), Inches(left), Inches(top), Inches(width))
    return pic


def add_notes(slide, text):
    """Add speaker notes."""
    notes_slide = slide.notes_slide
    notes_slide.notes_text_frame.text = text


# ============================================================
# SLIDE 1: Title slide
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "STDN Explorer", left=0.5, top=2.0, width=12.3, size=44)
txBox = slide.shapes.add_textbox(Inches(0.5), Inches(3.2), Inches(12.3), Inches(1.5))
tf = txBox.text_frame
tf.word_wrap = True
p = tf.paragraphs[0]
p.text = "Supply Chain Dependency Analysis Dashboard"
p.font.size = Pt(24)
p.font.color.rgb = ACCENT_COLOR
p = tf.add_paragraph()
p.text = ""
p = tf.add_paragraph()
p.text = "Interactive exploration of technology supply chains across"
p.font.size = Pt(16)
p.font.color.rgb = SUBTLE_COLOR
p = tf.add_paragraph()
p.text = "microelectronics, biotechnology, and pharmaceuticals"
p.font.size = Pt(16)
p.font.color.rgb = SUBTLE_COLOR
add_notes(slide, "Suppose you need to assess the potential impact of a sizeable reduction in Helium production from Qatar. Where do you start? How many technologies are affected, how concentrated is the market, and what does the US import picture actually look like? STDN Explorer is a supply chain analysis dashboard that maps technologies down to the raw materials and countries they depend on. The 180 technologies across 3 domains shown here are a limited sample for demonstration purposes. The data was generated by a novel AI agent pipeline, which we will describe at the end of this presentation.")

# ============================================================
# SLIDE 2: What is an STDN?
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "What is an STDN?")
add_bullets(slide, [
    "Shallow Technology Dependency Network",
    "4-layer directed graph: Technology > Component > Material > Country",
    "Maps the full supply chain for each technology",
    "180 technologies across 3 domains (demonstration sample)",
    "Domain-agnostic: scales to hundreds of domains, thousands of technologies",
    "New domains can be added without application changes",
], left=0.5, top=1.5, width=12.3, size=18)
add_notes(slide, "STDN Explorer maps four layers of dependency for each technology, starting from the finished technology, down through its procurable components, to the raw materials those components require, and finally to the countries that produce those materials. The 180 technologies across 3 domains shown here are a limited sample for demonstration purposes. A fully deployed system could handle hundreds of domains and thousands of technologies.")

# ============================================================
# SLIDE 3: Material Network
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "Material Network")
add_subtitle(slide, "How many technologies depend on a single material?")
add_bullets(slide, [
    "Select a material, see every technology that depends on it",
    "Helium: 152 of 180 technologies across all 3 domains",
    "Organized by domain > subdomain > technology",
    "Click domain to drill in, double-click technology to navigate",
], left=0.5, top=1.8, width=5.5)
add_image(slide, SCREENSHOTS / "07_material_network_helium.png", left=6.5, top=1.5, width=6.3)
add_notes(slide, "We start with the Material Network. This view works in the opposite direction from the rest of the dashboard. Instead of picking a technology and looking at what it needs, we pick a material and see everything that depends on it. Selecting Helium, we immediately see 152 technologies across all three domains. Three rings of subdomains and technologies fan out from the center. This is not a niche material. It touches nearly everything in our sample dataset. Clicking a domain lets you drill into one sector at a time. Clicking a subdomain narrows the view further. Selecting Smartphone from here automatically switches to the Technology Network.")

# ============================================================
# SLIDE 4: Technology Network
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "Technology Network")
add_subtitle(slide, "Four-layer dependency graph for a single technology")
add_bullets(slide, [
    "Center: technology (e.g., Smartphone)",
    "Ring 2: procurable components",
    "Ring 3: raw materials (amber) and process consumables (purple)",
    "Ring 4: producing countries (red)",
    "Click any node for detail panel with production shares",
    "Navigation buttons jump to Concentration or Overlap views",
], left=0.5, top=1.8, width=5.5)
add_image(slide, SCREENSHOTS / "01_technology_network_smartphone.png", left=6.5, top=1.5, width=6.3)
add_notes(slide, "The technology is at the center, surrounded by its components, the materials those components need, and the countries that produce them. Clicking a component highlights its connections through the graph. Clicking the Helium node, we see it's a process consumable, shown in purple with a dashed edge. It's used during manufacturing for leak testing but is not in the final product. Selecting Qatar in the graph shows it holding 38.8% of global Helium production. Notice the navigation buttons in the detail panel. These let us jump directly to the Concentration or Overlap views with Helium already selected.")

# ============================================================
# SLIDE 5: Concentration
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "Concentration (HHI)")
add_subtitle(slide, "How concentrated is each material's production?")
add_bullets(slide, [
    "Herfindahl-Hirschman Index per material-technology pair",
    "Color coded: green (diversified) to red (near-monopoly)",
    "Helium HHI: 2,815 (high concentration)",
    "Qatar 38.8%, United States 35.3%, Algeria 5.9%",
    "Top two producers hold over 74% of global output",
    "40% cut to Qatar removes ~15.5% of world supply",
], left=0.5, top=1.8, width=5.5)
add_image(slide, SCREENSHOTS / "02_concentration_heatmap.png", left=6.5, top=1.5, width=6.3)
add_notes(slide, "The Concentration view shows a heatmap of HHI scores, a standard measure of market concentration. Materials are rows, technologies are columns. Red and orange cells mean production is controlled by a small number of countries. For the Smartphone, Helium's HHI is 2,815, which falls in the high concentration range. Only six countries produce it at any scale, and the top two, the United States and Qatar, account for over 74% of global output. A 40% cut to Qatar's production removes roughly 15.5% of world supply. In a market this concentrated, there is no spare capacity to absorb that.")

# ============================================================
# SLIDE 6: Dominance
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "Country Dominance")
add_subtitle(slide, "How many materials does each country control?")
add_bullets(slide, [
    "Ranks countries by top-producer count",
    "China: 746 materials | United States: 166 | Japan: 8",
    "Qatar: Low dominance, leads in just one material",
    "But that one material touches 173 technologies",
    "Average share: 36.2% | Maximum share: 38.8%",
    "Narrow but deep: one material, nearly every technology",
], left=0.5, top=1.8, width=5.5)
add_image(slide, SCREENSHOTS / "03_dominance_table.png", left=6.5, top=1.5, width=6.3)
add_notes(slide, "The Dominance view ranks countries by how many materials they lead in. China and the United States dominate hundreds of materials. Qatar appears further down with a Low classification. It leads in just one material. But look at the reach: 60 out of 60 technologies affected in the Microelectronics domain alone, with an average share of 36.2%. Qatar's risk profile is narrow but deep. One material, nearly every technology.")

# ============================================================
# SLIDE 7: Overlap
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "Cross-Technology Overlap")
add_subtitle(slide, "Which materials and countries are systemic single points of failure?")
add_bullets(slide, [
    "Shared Materials: Helium in 152 technologies (3rd most shared)",
    "Both widely shared AND highly concentrated",
    "Shared Countries: Qatar supplies 173 technologies",
    "Through only 10 materials at 36.2% average share",
    "Compare: China touches 180 technologies through 920 materials",
    "A disruption hits 152 technologies in parallel, not in sequence",
], left=0.5, top=1.8, width=5.5)
add_image(slide, SCREENSHOTS / "04_overlap_systemic_risk.png", left=6.5, top=1.5, width=6.3)
add_notes(slide, "The Overlap view answers a direct question: if Qatar's Helium output drops, how many technologies feel it at once? Helium is the third most widely shared material in the dataset, appearing in 152 technologies with an HHI of 2,815. Switching to Shared Countries, Qatar shows up touching 173 technologies but through only 10 materials. Compare that to China at the top, which touches 180 technologies through 920 materials. Qatar's exposure is concentrated in a single commodity.")

# ============================================================
# SLIDE 8: Supply Disruption
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "Supply Disruption Simulator")
add_subtitle(slide, "What if a country stops producing?")
add_bullets(slide, [
    "Select a country, model complete production removal",
    "Qatar: 0 Critical, 152 High, 173 technologies affected",
    "Every Helium-dependent technology gets High severity",
    "Expand rows to see affected materials and components",
    "Severity thresholds based on EC Critical Raw Materials methodology",
    "For partial reductions, scale the results proportionally",
], left=0.5, top=1.8, width=5.5)
add_image(slide, SCREENSHOTS / "05_disruption_qatar.png", left=6.5, top=1.5, width=6.3)
add_notes(slide, "The Supply Disruption simulator models what happens if a country stops producing entirely. Selecting Qatar: zero Critical, 152 High severity technologies, 173 total affected. Every Helium-dependent technology gets a High rating because Qatar holds 38.8% of production. Expanding any row shows the specific materials and components at risk. The simulator models complete removal. For the 40% partial reduction, you would scale the results. Qatar's 38.8% share reduced by 40% means a loss of about 15.5 percentage points of global Helium supply.")

# ============================================================
# SLIDE 9: Trade Disruption
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "Trade Disruption (Comtrade)")
add_subtitle(slide, "What do actual US import flows show?")
add_bullets(slide, [
    "Based on UN Comtrade US import data (dollars, multi-year)",
    "Production share and trade flow often tell different stories",
    "Qatar: top US Helium import source through 2021",
    "Canada replaced Qatar starting 2022, reaching 100% by 2025",
    "Substitutability: only 2 countries in top position across 9 years",
    "Global supply shock vs. direct US import exposure",
], left=0.5, top=1.8, width=5.5)
add_image(slide, SCREENSHOTS / "08_trade_disruption_heatmap.png", left=6.5, top=1.5, width=6.3)
add_notes(slide, "The Trade Disruption view uses a different data source: actual US import values from UN Comtrade. Here the story diverges from the production share picture. Qatar was the single most disruptive country to remove from 2017 through 2021. But starting in 2022, Canada replaced Qatar as the top disruption source, with scores climbing to 100% by 2025. A Qatar production cut still tightens global supply and prices, but the direct US import exposure has shifted. The Substitutability tab confirms Helium's lock-in: only 2 distinct countries have held the top supplier position across 9 years.")

# ============================================================
# SLIDE 10: Analyst + Gemini
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "Policy Analyst + AI Chat")
add_subtitle(slide, "Structured reports and conversational follow-up")
add_bullets(slide, [
    "Six report templates (technology, country, material, etc.)",
    "Helium report: 152 affected technologies, systemic risk flag",
    "Recommendations: diversify sourcing, reduce concentration",
    "Ask Gemini sidebar for free-form questions",
    "Full dataset as context for AI responses",
    "Example: \"What is the trade disruption impact of a 40%",
    "    reduction in Qatar Helium production?\"",
], left=0.5, top=1.8, width=5.5)
add_image(slide, SCREENSHOTS / "10_analyst_gemini_response.png", left=6.5, top=1.5, width=6.3)
add_notes(slide, "The Analyst section pulls everything together. Selecting the Disruption impact of a material template for Helium generates a structured report: material overview, top producers, affected technologies, systemic risk assessment, and recommendations. The Ask Gemini sidebar lets you ask follow-up questions using the full dataset as context. Asking specifically about the 40% Qatar reduction, Gemini calculates a 15.5% global supply reduction and flags the systemic risk across all 152 dependent technologies.")

# ============================================================
# SLIDE 11: Data Pipeline
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "How the Data is Built")
add_subtitle(slide, "Multi-agent AI pipeline with USGS grounding")
add_image(slide, ASSETS / "pipeline_diagram.png", left=0.5, top=1.5, width=12.3)
add_notes(slide, "The data behind this dashboard was not assembled by hand. It was constructed by a pipeline of AI agents that debate each layer of the supply chain. Multiple agents independently propose the components a technology requires, then reconcile their proposals through rounds of structured debate until they converge. The same process repeats for materials. Country production data is pulled from USGS Mineral Commodity Summaries where available, with agent-estimated fallbacks where it is not. Every row carries a confidence score and a provenance tag showing whether the data comes from USGS or from agent consensus. A single technology takes about 30 minutes to map through all four layers. The 180 technologies across 3 domains shown here are a sample created for demonstration purposes. A fully deployed system could handle hundreds of domains and thousands of technologies. This sample was built in parallel batch runs in a single day, as opposed to months of manual research.")

# ============================================================
# SLIDE 12: Key Numbers
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "By the Numbers")

stats = [
    ("180", "technologies mapped"),
    ("3", "industry domains"),
    ("~900", "distinct materials"),
    ("~140", "producing countries"),
    ("43,000+", "supply chain links"),
    ("~30 min", "per technology to generate"),
    ("1 day", "to build entire sample dataset"),
]

for i, (num, label) in enumerate(stats):
    col = i % 4
    row = i // 4
    x = 0.5 + col * 3.2
    y = 1.8 + row * 2.5

    # Number
    txBox = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(2.8), Inches(0.8))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = num
    p.font.size = Pt(36)
    p.font.color.rgb = ACCENT_COLOR
    p.font.bold = True

    # Label
    txBox = slide.shapes.add_textbox(Inches(x), Inches(y + 0.7), Inches(2.8), Inches(0.5))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = label
    p.font.size = Pt(16)
    p.font.color.rgb = SUBTLE_COLOR

add_notes(slide, "The system maps 180 technologies across 3 domains, covering roughly 900 distinct materials, 140 producing countries, and over 43,000 supply chain links. Each technology takes about 30 minutes to process. The entire demonstration dataset was built in one day.")

# ============================================================
# SLIDE 13: Access
# ============================================================
slide = prs.slides.add_slide(blank_layout)
set_slide_bg(slide)
add_title(slide, "Try It", left=0.5, top=2.5, width=12.3, size=36)

txBox = slide.shapes.add_textbox(Inches(0.5), Inches(3.5), Inches(12.3), Inches(2.0))
tf = txBox.text_frame
tf.word_wrap = True
p = tf.paragraphs[0]
p.text = "Dashboard: dads2busy.github.io/stdn-explorer"
p.font.size = Pt(20)
p.font.color.rgb = ACCENT_COLOR
p = tf.add_paragraph()
p.text = ""
p = tf.add_paragraph()
p.text = "Source code: github.com/dads2busy/stdn-explorer"
p.font.size = Pt(16)
p.font.color.rgb = BULLET_COLOR
p = tf.add_paragraph()
p.text = "Video walkthrough: see GitHub Releases"
p.font.size = Pt(16)
p.font.color.rgb = BULLET_COLOR
p = tf.add_paragraph()
p.text = ""
p = tf.add_paragraph()
p.text = "No installation, login, or backend server required."
p.font.size = Pt(14)
p.font.color.rgb = SUBTLE_COLOR

add_notes(slide, "The dashboard is deployed at dads2busy.github.io/stdn-explorer and requires no installation, login, or backend server. Source code, data, and documentation are at github.com/dads2busy/stdn-explorer.")


prs.save(str(OUTPUT))
print(f"Done - {len(prs.slides)} slides saved to {OUTPUT}")
print(f"Size: {OUTPUT.stat().st_size / 1024 / 1024:.1f} MB")
