/**
 * Create STDN Explorer presentation using pptxgenjs.
 * Dark theme matching the dashboard aesthetic with varied layouts.
 */

import pptxgen from "pptxgenjs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DOCS = path.join(__dirname, "..", "docs");
const SCREENSHOTS = path.join(DOCS, "writeup_screenshots");
const ASSETS = path.join(DOCS, "video_assets");
const OUTPUT = path.join(DOCS, "STDN_Explorer_Presentation.pptx");

// Theme
const BG = "0F1729";
const BG_CARD = "1E293B";
const TITLE = "E2E8F0";
const BODY = "CBD5E1";
const ACCENT = "F59E0B";
const SUBTLE = "94A3B8";
const INDIGO = "6366F1";
const GREEN = "22C55E";
const RED = "EF4444";

const pres = new pptxgen();
pres.layout = "LAYOUT_WIDE"; // 13.33" x 7.5"
pres.author = "STDN Explorer";
pres.title = "STDN Explorer: Supply Chain Analysis Dashboard";

// ============================================================
// SLIDE 1: Title
// ============================================================
{
  const slide = pres.addSlide();
  slide.background = { color: BG };

  // Accent bar at top
  slide.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 0, w: 13.33, h: 0.06,
    fill: { color: ACCENT },
  });

  slide.addText("STDN Explorer", {
    x: 0.8, y: 2.0, w: 11.7, h: 1.2,
    fontSize: 48, fontFace: "Calibri", color: TITLE, bold: true,
    margin: 0,
  });

  slide.addText("Supply Chain Dependency Analysis Dashboard", {
    x: 0.8, y: 3.3, w: 11.7, h: 0.7,
    fontSize: 24, fontFace: "Calibri", color: ACCENT,
    margin: 0,
  });

  slide.addText([
    { text: "Interactive exploration of technology supply chains across", options: { breakLine: true } },
    { text: "microelectronics, biotechnology, and pharmaceuticals" },
  ], {
    x: 0.8, y: 4.3, w: 11.7, h: 0.9,
    fontSize: 16, fontFace: "Calibri", color: SUBTLE,
    margin: 0,
  });

  // Stats bar at bottom
  slide.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 6.2, w: 13.33, h: 1.3,
    fill: { color: "141B2D" },
  });

  const stats = [
    ["180", "technologies"], ["3", "domains"], ["~900", "materials"],
    ["~140", "countries"], ["43,000+", "supply chain links"],
  ];
  stats.forEach(([num, label], i) => {
    const x = 0.8 + i * 2.5;
    slide.addText(num, {
      x, y: 6.35, w: 2.2, h: 0.55,
      fontSize: 24, fontFace: "Calibri", color: ACCENT, bold: true,
      margin: 0,
    });
    slide.addText(label, {
      x, y: 6.85, w: 2.2, h: 0.4,
      fontSize: 12, fontFace: "Calibri", color: SUBTLE,
      margin: 0,
    });
  });

  slide.addNotes("Suppose you need to assess the potential impact of a sizeable reduction in Helium production from Qatar. Where do you start? How many technologies are affected, how concentrated is the market, and what does the US import picture actually look like? STDN Explorer is a supply chain analysis dashboard that maps technologies down to the raw materials and countries they depend on. The 180 technologies across 3 domains shown here are a limited sample for demonstration purposes. The data was generated by a novel AI agent pipeline, which we will describe at the end of this presentation.");
}

// ============================================================
// SLIDE 2: What is the STDN Explorer?
// ============================================================
{
  const slide = pres.addSlide();
  slide.background = { color: BG };

  slide.addText("What is the STDN Explorer?", {
    x: 0.8, y: 0.4, w: 11.7, h: 0.8,
    fontSize: 36, fontFace: "Calibri", color: TITLE, bold: true,
    margin: 0,
  });

  slide.addText("A web dashboard for investigating supply chain vulnerabilities across technology sectors. It maps each technology down to its components, raw materials, and the countries that produce them.", {
    x: 0.8, y: 1.4, w: 11.7, h: 0.9,
    fontSize: 16, fontFace: "Calibri", color: BODY,
    margin: 0,
  });

  // Three feature cards
  const features = [
    {
      title: "9 analytical views",
      desc: "Network graphs, heatmaps, country rankings, disruption simulators, trade flow analysis, and AI-assisted policy reports",
      color: INDIGO,
    },
    {
      title: "AI-generated data",
      desc: "Supply chain networks built by multi-agent debate in hours, not months. Grounded in USGS data with confidence scores on every row",
      color: GREEN,
    },
    {
      title: "Scalable by design",
      desc: "180 technologies across 3 domains as a sample. New domains and technologies added by loading CSV files, no code changes needed",
      color: ACCENT,
    },
  ];

  features.forEach((f, i) => {
    const x = 0.8 + i * 4.0;
    // Card
    slide.addShape(pres.shapes.RECTANGLE, {
      x, y: 2.8, w: 3.7, h: 2.8,
      fill: { color: BG_CARD },
      line: { color: f.color, width: 1.5 },
    });
    // Left accent bar
    slide.addShape(pres.shapes.RECTANGLE, {
      x, y: 2.8, w: 0.06, h: 2.8,
      fill: { color: f.color },
    });
    // Title
    slide.addText(f.title, {
      x: x + 0.3, y: 3.0, w: 3.1, h: 0.5,
      fontSize: 16, fontFace: "Calibri", color: f.color, bold: true,
      margin: 0,
    });
    // Description
    slide.addText(f.desc, {
      x: x + 0.3, y: 3.6, w: 3.1, h: 1.8,
      fontSize: 12, fontFace: "Calibri", color: SUBTLE,
      margin: 0, valign: "top",
    });
  });

  slide.addText("Live at dads2busy.github.io/stdn-explorer \u2014 no installation required", {
    x: 0.8, y: 6.2, w: 11.7, h: 0.5,
    fontSize: 13, fontFace: "Calibri", color: SUBTLE, italic: true,
    margin: 0,
  });

  slide.addNotes("STDN Explorer is a web dashboard for investigating supply chain vulnerabilities. It maps four layers of dependency for each technology: the finished product, its procurable components, the raw materials those components require, and the countries that produce those materials. The current dataset covers three domains with 60 technologies each. This is a demonstration sample. The system is domain-agnostic and can scale to hundreds of domains and thousands of technologies.");
}

// ============================================================
// SLIDE 3: What is an STDN?
// ============================================================
{
  const slide = pres.addSlide();
  slide.background = { color: BG };

  slide.addText("What is an STDN?", {
    x: 0.8, y: 0.4, w: 11.7, h: 0.8,
    fontSize: 36, fontFace: "Calibri", color: TITLE, bold: true,
    margin: 0,
  });

  // 4-layer flow diagram using cards
  const layers = [
    { label: "Technology", sub: "Smartphone, MRI Machine...", color: INDIGO, x: 0.8 },
    { label: "Component", sub: "Display Module, Battery...", color: GREEN, x: 3.8 },
    { label: "Material", sub: "Indium, Cobalt, Helium...", color: ACCENT, x: 6.8 },
    { label: "Country", sub: "China, Qatar, US...", color: RED, x: 9.8 },
  ];

  layers.forEach((l, i) => {
    // Card background
    slide.addShape(pres.shapes.RECTANGLE, {
      x: l.x, y: 1.6, w: 2.7, h: 1.6,
      fill: { color: BG_CARD },
      line: { color: l.color, width: 1.5 },
    });
    // Layer name
    slide.addText(l.label, {
      x: l.x, y: 1.7, w: 2.7, h: 0.6,
      fontSize: 18, fontFace: "Calibri", color: l.color, bold: true,
      align: "center", margin: 0,
    });
    // Examples
    slide.addText(l.sub, {
      x: l.x + 0.2, y: 2.3, w: 2.3, h: 0.7,
      fontSize: 11, fontFace: "Calibri", color: SUBTLE,
      align: "center", margin: 0,
    });
    // Arrow
    if (i < 3) {
      slide.addShape(pres.shapes.LINE, {
        x: l.x + 2.7, y: 2.4, w: 0.3, h: 0,
        line: { color: SUBTLE, width: 2 },
      });
    }
  });

  // Key points below
  slide.addText([
    { text: "180 technologies across 3 domains (demonstration sample)", options: { bullet: true, breakLine: true } },
    { text: "Domain-agnostic: scales to hundreds of domains, thousands of technologies", options: { bullet: true, breakLine: true } },
    { text: "New domains added by loading CSV files, no application changes needed", options: { bullet: true, breakLine: true } },
    { text: "Every row carries confidence scores and USGS/LLM provenance tags", options: { bullet: true } },
  ], {
    x: 0.8, y: 3.8, w: 11.7, h: 3.0,
    fontSize: 16, fontFace: "Calibri", color: BODY,
    paraSpaceAfter: 10,
  });

  slide.addNotes("STDN Explorer maps four layers of dependency for each technology, starting from the finished technology, down through its procurable components, to the raw materials those components require, and finally to the countries that produce those materials. The 180 technologies across 3 domains shown here are a limited sample for demonstration purposes. A fully deployed system could handle hundreds of domains and thousands of technologies.");
}

// ============================================================
// Helper: content slide with image on right
// ============================================================
function contentSlide({ title, description, bullets, image, notes, imageTop }) {
  const slide = pres.addSlide();
  slide.background = { color: BG };

  // Text area: ~35% width (left side)
  const textW = 4.2;
  let yPos = 0.4;

  // Title
  slide.addText(title, {
    x: 0.6, y: yPos, w: textW, h: 0.7,
    fontSize: 28, fontFace: "Calibri", color: TITLE, bold: true,
    margin: 0,
  });
  yPos += 0.8;

  // Description paragraph (what this view does)
  if (description) {
    // Estimate height needed: ~45 chars per line at 16pt in 4.2" wide box, ~0.3" per line
    const estimatedLines = Math.ceil(description.length / 40);
    const descHeight = Math.max(1.2, estimatedLines * 0.32);
    slide.addText(description, {
      x: 0.6, y: yPos, w: textW, h: descHeight,
      fontSize: 16, fontFace: "Calibri", color: SUBTLE,
      margin: 0, valign: "top",
    });
    yPos += descHeight + 0.2;
  }

  // Helium example label
  slide.addText("HELIUM / QATAR", {
    x: 0.6, y: yPos, w: textW, h: 0.35,
    fontSize: 10, fontFace: "Calibri", color: ACCENT, bold: true,
    charSpacing: 3, margin: 0,
  });
  yPos += 0.4;

  // Example bullets
  const bulletItems = bullets.map((b, i) => ({
    text: b,
    options: { bullet: true, ...(i < bullets.length - 1 ? { breakLine: true } : {}) },
  }));

  slide.addText(bulletItems, {
    x: 0.6, y: yPos, w: textW, h: 7.5 - yPos - 0.5,
    fontSize: 13, fontFace: "Calibri", color: BODY,
    paraSpaceAfter: 6, valign: "top",
  });

  // Image on right: ~65% width
  if (image) {
    const imgLeft = 5.1;
    const imgW = 7.8;
    const imgH = imgW * 0.625;
    const imgTop2 = imageTop || 0.6;
    slide.addShape(pres.shapes.RECTANGLE, {
      x: imgLeft - 0.1, y: imgTop2 - 0.1, w: imgW + 0.2, h: imgH + 0.2,
      fill: { color: BG_CARD },
      line: { color: "334155", width: 1 },
    });
    slide.addImage({
      path: image,
      x: imgLeft, y: imgTop2, w: imgW, h: imgH,
      sizing: { type: "contain", w: imgW, h: imgH },
    });
  }

  if (notes) slide.addNotes(notes);
  return slide;
}

// ============================================================
// SLIDE 3: Material Network
// ============================================================
contentSlide({
  title: "Material Network",
  description: "Select a material and see every technology that depends on it. The graph organizes dependencies by domain, subdomain, and technology. Click domains to drill in; double-click a technology to navigate to its full network.",
  bullets: [
    "Helium: 152 of 180 technologies across all 3 domains",
    "Spans microelectronics, biotech, and pharma",
    "Not a niche material; touches nearly everything",
  ],
  image: path.join(SCREENSHOTS, "07_material_network_helium.png"),
  notes: "We start with the Material Network. This view works in the opposite direction from the rest of the dashboard. Instead of picking a technology and looking at what it needs, we pick a material and see everything that depends on it. Selecting Helium, we immediately see 152 technologies across all three domains. This is not a niche material. It touches nearly everything in our sample dataset.",
});

// ============================================================
// SLIDE 4: Technology Network
// ============================================================
contentSlide({
  title: "Technology Network",
  description: "Four concentric rings map each technology's full supply chain. Click any node for production shares, confidence scores, and data provenance. Navigation buttons jump to related analytical views.",
  bullets: [
    "Helium appears as a purple process consumable node",
    "Used for leak testing, not in the final product",
    "Qatar holds 38.8% of global Helium production",
  ],
  image: path.join(SCREENSHOTS, "01_technology_network_smartphone.png"),
  notes: "The technology is at the center, surrounded by its components, the materials those components need, and the countries that produce them. Clicking the Helium node, we see it's a process consumable, shown in purple with a dashed edge. It's used during manufacturing for leak testing but is not in the final product. Selecting Qatar in the graph shows it holding 38.8% of global Helium production.",
});

// ============================================================
// SLIDE 5: Concentration
// ============================================================
contentSlide({
  title: "Concentration (HHI)",
  description: "Herfindahl-Hirschman Index measures how concentrated each material's production is among countries. The heatmap shows HHI per material-technology pair, color coded from green (diversified) to red (near-monopoly).",
  bullets: [
    "Helium HHI: 2,815 (high concentration)",
    "Qatar 38.8%, US 35.3%, Algeria 5.9%",
    "Top two hold over 74% of global output",
    "A 40% cut to Qatar removes ~15.5% of world supply",
  ],
  image: path.join(SCREENSHOTS, "02_concentration_heatmap.png"),
  notes: "The Concentration view shows a heatmap of HHI scores, a standard measure of market concentration. For the Smartphone, Helium's HHI is 2,815, which falls in the high concentration range. Only six countries produce it at any scale, and the top two account for over 74% of global output. A 40% cut to Qatar's production removes roughly 15.5% of world supply.",
});

// ============================================================
// SLIDE 6: Dominance
// ============================================================
contentSlide({
  title: "Country Dominance",
  description: "Ranks countries by the number of materials for which they are the world's top producer. China leads with 746 materials, the United States with 166, Japan with 8.",
  bullets: [
    "Qatar: Low dominance, leads in just one material",
    "But that one material touches 173 technologies",
    "Average share: 36.2%",
    "Narrow but deep: one material, nearly every technology",
  ],
  image: path.join(SCREENSHOTS, "03_dominance_table.png"),
  notes: "The Dominance view ranks countries by how many materials they lead in. Qatar appears further down with a Low classification. It leads in just one material. But look at the reach: 60 out of 60 technologies affected in the Microelectronics domain alone, with an average share of 36.2%. Qatar's risk profile is narrow but deep.",
});

// ============================================================
// SLIDE 7: Overlap
// ============================================================
contentSlide({
  title: "Cross-Technology Overlap",
  description: "Identifies materials and countries shared across many technologies, where a single disruption propagates widely. Shared Materials tab lists materials by technology count; Shared Countries tab shows which countries supply the most technologies.",
  bullets: [
    "Helium: 3rd most shared material, in 152 technologies",
    "Qatar: 173 technologies through only 10 materials",
    "Compare: China touches 180 through 920 materials",
    "A disruption hits 152 technologies in parallel",
  ],
  image: path.join(SCREENSHOTS, "04_overlap_systemic_risk.png"),
  notes: "The Overlap view answers a direct question: if Qatar's Helium output drops, how many technologies feel it at once? Helium is the third most widely shared material in the dataset. Switching to Shared Countries, Qatar shows up touching 173 technologies but through only 10 materials. Qatar's exposure is concentrated in a single commodity.",
});

// ============================================================
// SLIDE 8: Supply Disruption
// ============================================================
contentSlide({
  title: "Supply Disruption",
  description: "Simulates the impact of a country ceasing all production. Shows affected technologies by severity (Critical/High/Moderate/Low). Expand rows to see specific materials and components at risk.",
  bullets: [
    "Qatar: 0 Critical, 152 High, 173 total affected",
    "Every Helium-dependent technology gets High severity",
    "38.8% maximum share lost",
    "For a 40% partial reduction, scale proportionally",
  ],
  image: path.join(SCREENSHOTS, "05_disruption_qatar.png"),
  notes: "The Supply Disruption simulator models what happens if a country stops producing entirely. Selecting Qatar: zero Critical, 152 High severity technologies, 173 total affected. Every Helium-dependent technology gets a High rating because Qatar holds 38.8% of production.",
});

// ============================================================
// SLIDE 9: Trade Disruption
// ============================================================
contentSlide({
  title: "Trade Disruption",
  description: "Uses actual US import values from UN Comtrade (in dollars, across multiple years). Production share and trade flow often tell different stories. The Substitutability tab measures supplier lock-in over time.",
  bullets: [
    "Qatar: top US Helium import source through 2021",
    "Canada replaced Qatar starting 2022 (100% by 2025)",
    "Only 2 countries in top position across 9 years",
    "Global supply shock vs. direct US import exposure",
  ],
  image: path.join(SCREENSHOTS, "08_trade_disruption_heatmap.png"),
  notes: "The Trade Disruption view uses actual US import values from UN Comtrade. Qatar was the top disruption source through 2021. Starting in 2022, Canada replaced it. The Substitutability tab confirms Helium's lock-in: only 2 distinct countries have held the top supplier position across 9 years.",
});

// ============================================================
// SLIDE 10: Analyst + Gemini
// ============================================================
contentSlide({
  title: "Policy Analyst + AI Chat",
  description: "Generates structured policy reports from six templates. An optional AI chat sidebar (Ask Gemini) allows free-form follow-up questions with the full supply chain dataset as context.",
  bullets: [
    "Helium report: 152 affected technologies, systemic risk",
    "Recommendations: diversify sourcing, reduce concentration",
    "Gemini calculates 15.5% global supply reduction",
    "Flags systemic risk across all 152 technologies",
  ],
  image: path.join(SCREENSHOTS, "10_analyst_gemini_response.png"),
  notes: "The Analyst section pulls everything together. Selecting the Disruption impact of a material template for Helium generates a structured report. The Ask Gemini sidebar lets you ask follow-up questions. Asking about the 40% Qatar reduction, Gemini calculates a 15.5% global supply reduction and flags the systemic risk across all 152 dependent technologies.",
});

// ============================================================
// SLIDE 11: Data Pipeline (full-width image)
// ============================================================
{
  const slide = pres.addSlide();
  slide.background = { color: BG };

  slide.addText("How the Data is Built", {
    x: 0.8, y: 0.3, w: 11.7, h: 0.7,
    fontSize: 32, fontFace: "Calibri", color: TITLE, bold: true,
    margin: 0,
  });

  slide.addText("Multi-agent AI pipeline with USGS grounding", {
    x: 0.8, y: 0.95, w: 11.7, h: 0.4,
    fontSize: 14, fontFace: "Calibri", color: ACCENT, bold: true,
    margin: 0,
  });

  slide.addImage({
    path: path.join(ASSETS, "pipeline_diagram.png"),
    x: 0.4, y: 1.5, w: 12.5, h: 5.7,
    sizing: { type: "contain", w: 12.5, h: 5.7 },
  });

  slide.addNotes("The data behind this dashboard was not assembled by hand. It was constructed by a pipeline of AI agents that debate each layer of the supply chain. Multiple agents independently propose the components a technology requires, then reconcile their proposals through rounds of structured debate until they converge. Country production data is pulled from USGS Mineral Commodity Summaries where available. A single technology takes about 30 minutes. The 180 technologies were built in parallel batch runs in a single day, as opposed to months of manual research.");
}

// ============================================================
// SLIDE 12: Key Numbers
// ============================================================
{
  const slide = pres.addSlide();
  slide.background = { color: BG };

  slide.addText("By the Numbers", {
    x: 0.8, y: 0.4, w: 11.7, h: 0.8,
    fontSize: 36, fontFace: "Calibri", color: TITLE, bold: true,
    margin: 0,
  });

  const stats = [
    { num: "180", label: "technologies mapped", color: INDIGO },
    { num: "3", label: "industry domains", color: GREEN },
    { num: "~900", label: "distinct materials", color: ACCENT },
    { num: "~140", label: "producing countries", color: RED },
    { num: "43,000+", label: "supply chain links", color: INDIGO },
    { num: "~30 min", label: "per technology", color: GREEN },
    { num: "1 day", label: "to build full sample", color: ACCENT },
    { num: "0.95", label: "USGS confidence score", color: RED },
  ];

  stats.forEach((s, i) => {
    const col = i % 4;
    const row = Math.floor(i / 4);
    const x = 0.8 + col * 3.1;
    const y = 1.8 + row * 2.5;

    // Card
    slide.addShape(pres.shapes.RECTANGLE, {
      x, y, w: 2.8, h: 2.0,
      fill: { color: BG_CARD },
      line: { color: "334155", width: 1 },
    });

    // Number
    slide.addText(s.num, {
      x, y: y + 0.3, w: 2.8, h: 0.8,
      fontSize: 32, fontFace: "Calibri", color: s.color, bold: true,
      align: "center", margin: 0,
    });

    // Label
    slide.addText(s.label, {
      x, y: y + 1.2, w: 2.8, h: 0.5,
      fontSize: 13, fontFace: "Calibri", color: SUBTLE,
      align: "center", margin: 0,
    });
  });

  slide.addNotes("The system maps 180 technologies across 3 domains, covering roughly 900 distinct materials, 140 producing countries, and over 43,000 supply chain links. Each technology takes about 30 minutes to process. The entire demonstration dataset was built in one day.");
}

// ============================================================
// SLIDE 13: Access
// ============================================================
{
  const slide = pres.addSlide();
  slide.background = { color: BG };

  // Accent bar at bottom
  slide.addShape(pres.shapes.RECTANGLE, {
    x: 0, y: 7.44, w: 13.33, h: 0.06,
    fill: { color: ACCENT },
  });

  slide.addText("Try It", {
    x: 0.8, y: 2.2, w: 11.7, h: 1.0,
    fontSize: 44, fontFace: "Calibri", color: TITLE, bold: true,
    margin: 0,
  });

  slide.addText("dads2busy.github.io/stdn-explorer", {
    x: 0.8, y: 3.5, w: 11.7, h: 0.6,
    fontSize: 22, fontFace: "Calibri", color: ACCENT,
    margin: 0,
  });

  slide.addText([
    { text: "Source: github.com/dads2busy/stdn-explorer", options: { breakLine: true } },
    { text: "Video walkthrough: see GitHub Releases", options: { breakLine: true } },
    { text: "", options: { breakLine: true } },
    { text: "No installation, login, or backend server required." },
  ], {
    x: 0.8, y: 4.4, w: 11.7, h: 2.0,
    fontSize: 16, fontFace: "Calibri", color: SUBTLE,
    paraSpaceAfter: 6, margin: 0,
  });

  slide.addNotes("The dashboard is deployed at dads2busy.github.io/stdn-explorer and requires no installation, login, or backend server. Source code, data, and documentation are at github.com/dads2busy/stdn-explorer.");
}

// Save
await pres.writeFile({ fileName: OUTPUT });
console.log(`Done - 13 slides saved to ${OUTPUT}`);
