"""Generate narration audio for the STDN Explorer video walkthrough.

Produces fine-grained audio segments aligned to action cue points.
Each segment corresponds to narration that plays WHILE a specific
browser action is visible. The measured duration of each segment
is written to a JSON file for the Playwright recording script to use.
"""

import json
import os
from pathlib import Path
from openai import OpenAI

env_path = Path.home() / "git" / "dpi_stdn_agentic" / ".env"
for line in env_path.read_text().splitlines():
    if line.startswith("OPENAI_API_KEY="):
        os.environ["OPENAI_API_KEY"] = line.split("=", 1)[1].strip()
        break

client = OpenAI()
output_dir = Path(__file__).parent.parent / "docs" / "video_audio"
output_dir.mkdir(exist_ok=True)

VOICE = "nova"
MODEL = "tts-1-hd"

# Each entry: (segment_id, narration_text, action_description)
# The action_description is for documentation only; the Playwright script
# uses the segment_id and measured duration.
segments = [
    # === INTRO ===
    ("intro_hook",
     "Suppose you need to assess the potential impact of a sizeable reduction "
     "in Helium production from Qatar. "
     "Where do you start? How many technologies are affected, how concentrated is the market, "
     "and what does the US import picture actually look like?",
     "Dashboard loads, All Domains selected"),

    ("intro_context",
     "STDN Explorer is a supply chain analysis dashboard that maps technologies down to the "
     "raw materials and countries they depend on. "
     "The 180 technologies across 3 domains shown here are a limited sample for demonstration purposes. "
     "The data was generated by a novel AI agent pipeline, "
     "which we will describe at the end of this walkthrough. "
     "For now, let's focus on what the dashboard can do.",
     "Linger on Technology Network default view"),

    # === MATERIAL NETWORK ===
    ("mat_intro",
     "We start with the Material Network. This view works in the opposite direction from the "
     "rest of the dashboard. Instead of picking a technology and looking at what it needs, "
     "we pick a material and see everything that depends on it.",
     "Click Material Network tab"),

    ("mat_helium",
     "Selecting Helium, we immediately see 152 technologies across all three domains. "
     "Three rings of subdomains and technologies fan out from the center. "
     "This is not a niche material. It touches nearly everything in our sample dataset.",
     "Select Helium, let graph render"),

    ("mat_domain",
     "Clicking a domain lets you drill into one sector at a time.",
     "Click Microelectronics domain node"),

    ("mat_subdomain",
     "Clicking a subdomain narrows the view further. "
     "Here we can see individual technologies in Consumer Electronics.",
     "Click Consumer Electronics subdomain"),

    ("mat_smartphone",
     "Selecting Smartphone from here automatically switches to the Technology Network, "
     "where we can see its full four-layer dependency graph.",
     "Double-click Smartphone, auto-navigate to Technology Network"),

    # === TECHNOLOGY NETWORK ===
    ("tech_overview",
     "The technology is at the center, surrounded by its components, "
     "the materials those components need, and the countries that produce them.",
     "Let Technology Network graph render"),

    ("tech_component",
     "Clicking a component highlights its connections through the graph.",
     "Click a component node (e.g. Lithium-Ion Battery)"),

    ("tech_helium",
     "Clicking the Helium node, we see it's a process consumable, shown in purple with a dashed edge. "
     "It's used during manufacturing for leak testing but is not in the final product.",
     "Click Helium node"),

    ("tech_qatar",
     "Selecting Qatar in the graph shows it holding 38.8% of global Helium production. "
     "Clicking back to Helium, notice the navigation buttons in the detail panel. "
     "Clicking See Technology Material Country Concentration takes us directly to the "
     "Concentration view with the Smartphone and Helium intersection already selected.",
     "Click Qatar, re-click Helium, click concentration nav button"),

    # === CONCENTRATION ===
    ("conc_intro",
     "The Concentration view shows a heatmap of HHI scores, a standard measure of market "
     "concentration. Materials are rows, technologies are columns. Red and orange cells mean "
     "production is controlled by a small number of countries.",
     "Concentration view already loaded with Smartphone/Helium selected"),

    ("conc_helium",
     "For the Smartphone, Helium's HHI is 2,815, which falls in the high concentration range. "
     "Only six countries produce it at any scale, and the top two, the United States and Qatar, "
     "account for over 95% of global output. "
     "A 40% cut to Qatar's production removes roughly 15.5% of world supply. "
     "In a market this concentrated, there is no spare capacity to absorb that.",
     "Helium/Smartphone cell already selected via nav button"),

    # === DOMINANCE ===
    ("dom_intro",
     "The Dominance view ranks countries by how many materials they lead in. "
     "China and the United States dominate hundreds of materials. "
     "Qatar appears further down with a Low classification. It leads in just one material.",
     "Click Dominance tab, scroll to Qatar"),

    ("dom_qatar",
     "But look at the reach: 60 out of 60 technologies affected in the Microelectronics domain alone, "
     "with an average share of 36.2%. "
     "Qatar's risk profile is narrow but deep. One material, nearly every technology.",
     "Click Qatar row, show detail panel"),

    # === OVERLAP ===
    ("overlap_materials",
     "The Overlap view answers a direct question: if Qatar's Helium output drops, "
     "how many technologies feel it at once? "
     "Helium is the third most widely shared material in the dataset, appearing in "
     "152 technologies with an HHI of 2,815.",
     "Select All Domains, click Overlap tab, show Shared Materials"),

    ("overlap_countries",
     "Switching to Shared Countries, Qatar shows up touching 173 technologies but through "
     "only 10 materials. Compare that to China at the top, which touches 180 technologies "
     "through 920 materials. Qatar's exposure is concentrated in a single commodity.",
     "Click Shared Countries sub-tab, show Qatar"),

    # === SUPPLY DISRUPTION ===
    ("disrupt_intro",
     "The Supply Disruption simulator models what happens if a country stops producing entirely. "
     "Selecting Qatar: zero Critical, 152 High severity technologies, 173 total affected. "
     "Every Helium-dependent technology gets a High rating because Qatar holds 38.8% of production.",
     "Click Supply Disruption tab, select Qatar"),

    ("disrupt_expand",
     "Expanding any row shows the specific materials and components at risk.",
     "Expand Smartphone row"),

    # === TRADE DISRUPTION ===
    ("trade_intro",
     "The Trade Disruption view uses a different data source: actual US import values from "
     "UN Comtrade. Here the story diverges from the production share picture.",
     "Click Trade Disruption tab"),

    ("trade_helium",
     "Click the Helium column, and the detail panel shows year-by-year data. "
     "Qatar was the single most disruptive country to remove from 2017 through 2021, "
     "with disruption scores ranging from 29 to 48 percent. "
     "But starting in 2022, Canada replaced Qatar as the top disruption source, "
     "with scores climbing to 100% by 2025. "
     "A Qatar production cut still tightens global supply and prices, but the direct US import "
     "exposure has shifted.",
     "Click Helium column, show year-by-year detail"),

    ("trade_subst",
     "The Substitutability tab confirms Helium's lock-in: only 2 distinct countries have held "
     "the top supplier position across 9 years.",
     "Click Substitutability sub-tab, click Helium row"),

    # === ANALYST ===
    ("analyst_report",
     "Finally, the Analyst section pulls everything together. "
     "Selecting the Disruption impact of a material template for Helium generates a structured "
     "report: material overview, top producers, affected technologies, systemic risk assessment, "
     "and recommendations. "
     "Scrolling through, the report flags Helium as a systemic dependency shared across 152 "
     "technologies, and recommends diversifying sourcing, reducing single-country dependency, "
     "and coordinating procurement across the technologies that share this material.",
     "Click Analyst tab, select template, generate report, scroll through"),

    # === GEMINI ===
    ("gemini_query",
     "The Ask Gemini sidebar lets you ask follow-up questions using the full dataset as context. "
     "Asking specifically about the 40% Qatar reduction, Gemini calculates a 15.5% global supply "
     "reduction and flags the systemic risk across all 152 dependent technologies. "
     "It notes that while the United States is the top producer, "
     "the global supply shock would still disrupt the US market through increased prices and scarcity.",
     "Type query, send, wait for Gemini response"),

    # === TRANSITION ===
    ("transition",
     "That is what the dashboard can do. Now let's talk about where the data comes from.",
     "Pause on dashboard"),

    # === DATA ORIGIN ===
    ("data_origin",
     "The data behind this dashboard was not assembled by hand. "
     "It was constructed by a pipeline of AI agents that debate each layer of the supply chain. "
     "Multiple agents independently propose the components a technology requires, then reconcile "
     "their proposals through rounds of structured debate until they converge. "
     "The same process repeats for materials. "
     "Country production data is pulled from USGS Mineral Commodity Summaries where available, "
     "with agent-estimated fallbacks where it is not. "
     "Every row carries a confidence score and a provenance tag showing whether the data comes "
     "from USGS or from agent consensus. "
     "A single technology takes about 30 minutes to map through all four layers. "
     "The 180 technologies across 3 domains shown here are a sample created for demonstration purposes. "
     "A fully deployed system could handle hundreds of domains and thousands of technologies. "
     "This sample was built in parallel batch runs in a single day, "
     "as opposed to months of manual research.",
     "Show pipeline diagram"),

    # === CLOSING ===
    ("closing",
     "From a novel data pipeline to an interactive analytical dashboard, "
     "the system takes you from raw supply chain data to structured policy insights. "
     "The dashboard gives you the numbers. What you do with them is your call.",
     "Return to dashboard"),
]

# Generate audio and measure durations
durations = {}
for seg_id, text, action in segments:
    out_path = output_dir / f"{seg_id}.mp3"
    word_count = len(text.split())
    print(f"Generating {seg_id} ({word_count} words)...")
    with client.audio.speech.with_streaming_response.create(
        model=MODEL,
        voice=VOICE,
        input=text,
    ) as response:
        response.stream_to_file(str(out_path))

    # Measure actual duration using afinfo (macOS) or ffprobe
    import subprocess
    result = subprocess.run(
        ["afinfo", str(out_path)],
        capture_output=True, text=True
    )
    dur = 0.0
    for line in result.stdout.splitlines():
        if "estimated duration" in line:
            # Format: "estimated duration: 14.808000 sec"
            parts = line.split()
            for p in parts:
                try:
                    dur = float(p)
                    if dur > 0.1:
                        break
                except ValueError:
                    continue
            break

    durations[seg_id] = round(dur, 2)
    print(f"  -> {out_path.name} ({dur:.1f}s, {out_path.stat().st_size / 1024:.0f} KB)")

# Write durations JSON for the Playwright script
durations_path = output_dir / "segment_durations.json"
with open(durations_path, "w") as f:
    json.dump(durations, f, indent=2)

print(f"\nDurations written to {durations_path}")
print(f"Total narration: {sum(durations.values()):.1f}s ({sum(durations.values())/60:.1f}m)")
print(f"\nSegment order for stitch script:")
for seg_id, _, _ in segments:
    print(f"  {seg_id}")
